/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AuthService, DatabaseService, FireEnjinFetchEvent, FireEnjinTriggerInput } from "@fireenjin/sdk";
import { Message, User } from "./interfaces";
export { AuthService, DatabaseService, FireEnjinFetchEvent, FireEnjinTriggerInput } from "@fireenjin/sdk";
export { Message, User } from "./interfaces";
export namespace Components {
    interface AddRoom {
    }
    interface AppRouter {
    }
    interface ChatApp {
    }
    interface ModalLogin {
        "auth": AuthService;
        "userId": any;
    }
    interface PageChat {
        "db": DatabaseService;
        "messages": Message[];
        "roomId": string;
    }
    interface PageChatList {
    }
    interface PageHome {
        "auth": AuthService;
        "db": DatabaseService;
    }
    interface PageProfile {
        "db": DatabaseService;
        "user": User;
    }
    interface PageRoomList {
    }
    interface PopoverAddRoom {
    }
    interface PopoverEditProfile {
        "user": User;
    }
}
export interface ModalLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalLoginElement;
}
export interface PageChatCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPageChatElement;
}
export interface PageHomeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPageHomeElement;
}
export interface PageProfileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPageProfileElement;
}
export interface PageRoomListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPageRoomListElement;
}
declare global {
    interface HTMLAddRoomElement extends Components.AddRoom, HTMLStencilElement {
    }
    var HTMLAddRoomElement: {
        prototype: HTMLAddRoomElement;
        new (): HTMLAddRoomElement;
    };
    interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {
    }
    var HTMLAppRouterElement: {
        prototype: HTMLAppRouterElement;
        new (): HTMLAppRouterElement;
    };
    interface HTMLChatAppElement extends Components.ChatApp, HTMLStencilElement {
    }
    var HTMLChatAppElement: {
        prototype: HTMLChatAppElement;
        new (): HTMLChatAppElement;
    };
    interface HTMLModalLoginElement extends Components.ModalLogin, HTMLStencilElement {
    }
    var HTMLModalLoginElement: {
        prototype: HTMLModalLoginElement;
        new (): HTMLModalLoginElement;
    };
    interface HTMLPageChatElement extends Components.PageChat, HTMLStencilElement {
    }
    var HTMLPageChatElement: {
        prototype: HTMLPageChatElement;
        new (): HTMLPageChatElement;
    };
    interface HTMLPageChatListElement extends Components.PageChatList, HTMLStencilElement {
    }
    var HTMLPageChatListElement: {
        prototype: HTMLPageChatListElement;
        new (): HTMLPageChatListElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLPageRoomListElement extends Components.PageRoomList, HTMLStencilElement {
    }
    var HTMLPageRoomListElement: {
        prototype: HTMLPageRoomListElement;
        new (): HTMLPageRoomListElement;
    };
    interface HTMLPopoverAddRoomElement extends Components.PopoverAddRoom, HTMLStencilElement {
    }
    var HTMLPopoverAddRoomElement: {
        prototype: HTMLPopoverAddRoomElement;
        new (): HTMLPopoverAddRoomElement;
    };
    interface HTMLPopoverEditProfileElement extends Components.PopoverEditProfile, HTMLStencilElement {
    }
    var HTMLPopoverEditProfileElement: {
        prototype: HTMLPopoverEditProfileElement;
        new (): HTMLPopoverEditProfileElement;
    };
    interface HTMLElementTagNameMap {
        "add-room": HTMLAddRoomElement;
        "app-router": HTMLAppRouterElement;
        "chat-app": HTMLChatAppElement;
        "modal-login": HTMLModalLoginElement;
        "page-chat": HTMLPageChatElement;
        "page-chat-list": HTMLPageChatListElement;
        "page-home": HTMLPageHomeElement;
        "page-profile": HTMLPageProfileElement;
        "page-room-list": HTMLPageRoomListElement;
        "popover-add-room": HTMLPopoverAddRoomElement;
        "popover-edit-profile": HTMLPopoverEditProfileElement;
    }
}
declare namespace LocalJSX {
    interface AddRoom {
    }
    interface AppRouter {
    }
    interface ChatApp {
    }
    interface ModalLogin {
        "auth"?: AuthService;
        "onChatModalClose"?: (event: ModalLoginCustomEvent<any>) => void;
        "userId"?: any;
    }
    interface PageChat {
        "db"?: DatabaseService;
        "messages"?: Message[];
        "onFireenjinFetch"?: (event: PageChatCustomEvent<FireEnjinFetchEvent>) => void;
        "onFireenjinTrigger"?: (event: PageChatCustomEvent<FireEnjinTriggerInput>) => void;
        "roomId"?: string;
    }
    interface PageChatList {
    }
    interface PageHome {
        "auth"?: AuthService;
        "db"?: DatabaseService;
        "onChatModalOpen"?: (event: PageHomeCustomEvent<any>) => void;
    }
    interface PageProfile {
        "db"?: DatabaseService;
        "onFireenjinFetch"?: (event: PageProfileCustomEvent<FireEnjinFetchEvent>) => void;
        "user"?: User;
    }
    interface PageRoomList {
        "onFireenjinFetch"?: (event: PageRoomListCustomEvent<FireEnjinFetchEvent>) => void;
    }
    interface PopoverAddRoom {
    }
    interface PopoverEditProfile {
        "user"?: User;
    }
    interface IntrinsicElements {
        "add-room": AddRoom;
        "app-router": AppRouter;
        "chat-app": ChatApp;
        "modal-login": ModalLogin;
        "page-chat": PageChat;
        "page-chat-list": PageChatList;
        "page-home": PageHome;
        "page-profile": PageProfile;
        "page-room-list": PageRoomList;
        "popover-add-room": PopoverAddRoom;
        "popover-edit-profile": PopoverEditProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-room": LocalJSX.AddRoom & JSXBase.HTMLAttributes<HTMLAddRoomElement>;
            "app-router": LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
            "chat-app": LocalJSX.ChatApp & JSXBase.HTMLAttributes<HTMLChatAppElement>;
            "modal-login": LocalJSX.ModalLogin & JSXBase.HTMLAttributes<HTMLModalLoginElement>;
            "page-chat": LocalJSX.PageChat & JSXBase.HTMLAttributes<HTMLPageChatElement>;
            "page-chat-list": LocalJSX.PageChatList & JSXBase.HTMLAttributes<HTMLPageChatListElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "page-room-list": LocalJSX.PageRoomList & JSXBase.HTMLAttributes<HTMLPageRoomListElement>;
            "popover-add-room": LocalJSX.PopoverAddRoom & JSXBase.HTMLAttributes<HTMLPopoverAddRoomElement>;
            "popover-edit-profile": LocalJSX.PopoverEditProfile & JSXBase.HTMLAttributes<HTMLPopoverEditProfileElement>;
        }
    }
}
