/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AuthService, DatabaseService } from "@fireenjin/sdk";
export { AuthService, DatabaseService } from "@fireenjin/sdk";
export namespace Components {
    interface AppRouter {
    }
    interface ModalLogin {
        "auth": AuthService;
        "userId": any;
    }
    interface PageChatList {
    }
    interface PageHome {
        "auth": AuthService;
        "db": DatabaseService;
    }
    interface PageProfile {
        "name": string;
    }
    interface RoomsApp {
    }
    interface UsersApp {
    }
}
export interface ModalLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalLoginElement;
}
export interface PageHomeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPageHomeElement;
}
declare global {
    interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {
    }
    var HTMLAppRouterElement: {
        prototype: HTMLAppRouterElement;
        new (): HTMLAppRouterElement;
    };
    interface HTMLModalLoginElement extends Components.ModalLogin, HTMLStencilElement {
    }
    var HTMLModalLoginElement: {
        prototype: HTMLModalLoginElement;
        new (): HTMLModalLoginElement;
    };
    interface HTMLPageChatListElement extends Components.PageChatList, HTMLStencilElement {
    }
    var HTMLPageChatListElement: {
        prototype: HTMLPageChatListElement;
        new (): HTMLPageChatListElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLRoomsAppElement extends Components.RoomsApp, HTMLStencilElement {
    }
    var HTMLRoomsAppElement: {
        prototype: HTMLRoomsAppElement;
        new (): HTMLRoomsAppElement;
    };
    interface HTMLUsersAppElement extends Components.UsersApp, HTMLStencilElement {
    }
    var HTMLUsersAppElement: {
        prototype: HTMLUsersAppElement;
        new (): HTMLUsersAppElement;
    };
    interface HTMLElementTagNameMap {
        "app-router": HTMLAppRouterElement;
        "modal-login": HTMLModalLoginElement;
        "page-chat-list": HTMLPageChatListElement;
        "page-home": HTMLPageHomeElement;
        "page-profile": HTMLPageProfileElement;
        "rooms-app": HTMLRoomsAppElement;
        "users-app": HTMLUsersAppElement;
    }
}
declare namespace LocalJSX {
    interface AppRouter {
    }
    interface ModalLogin {
        "auth"?: AuthService;
        "onChatModalClose"?: (event: ModalLoginCustomEvent<any>) => void;
        "userId"?: any;
    }
    interface PageChatList {
    }
    interface PageHome {
        "auth"?: AuthService;
        "db"?: DatabaseService;
        "onChatModalOpen"?: (event: PageHomeCustomEvent<any>) => void;
    }
    interface PageProfile {
        "name"?: string;
    }
    interface RoomsApp {
    }
    interface UsersApp {
    }
    interface IntrinsicElements {
        "app-router": AppRouter;
        "modal-login": ModalLogin;
        "page-chat-list": PageChatList;
        "page-home": PageHome;
        "page-profile": PageProfile;
        "rooms-app": RoomsApp;
        "users-app": UsersApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-router": LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
            "modal-login": LocalJSX.ModalLogin & JSXBase.HTMLAttributes<HTMLModalLoginElement>;
            "page-chat-list": LocalJSX.PageChatList & JSXBase.HTMLAttributes<HTMLPageChatListElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "rooms-app": LocalJSX.RoomsApp & JSXBase.HTMLAttributes<HTMLRoomsAppElement>;
            "users-app": LocalJSX.UsersApp & JSXBase.HTMLAttributes<HTMLUsersAppElement>;
        }
    }
}
